"""align orm schema drift

Revision ID: d32ec5765c5d
Revises: 20260706_0008
Create Date: 2026-07-08 18:48:47.853448
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd32ec5765c5d'
down_revision: str | None = '20260706_0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'agent_trace',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.drop_index(op.f('idx_connection_attempts_action_created_at'), table_name='connection_attempts')
    op.create_index('idx_connection_attempts_action_created_at', 'connection_attempts', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('idx_connection_attempts_decision_created_at'), table_name='connection_attempts')
    op.create_index('idx_connection_attempts_decision_created_at', 'connection_attempts', ['decision', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('idx_connection_attempts_owner_id_created_at'), table_name='connection_attempts')
    op.create_index('idx_connection_attempts_owner_id_created_at', 'connection_attempts', ['owner_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('schema_snapshots', 'catalog_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_snapshots', 'catalog_json',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('idx_connection_attempts_owner_id_created_at', table_name='connection_attempts')
    op.create_index(op.f('idx_connection_attempts_owner_id_created_at'), 'connection_attempts', ['owner_id', 'created_at'], unique=False)
    op.drop_index('idx_connection_attempts_decision_created_at', table_name='connection_attempts')
    op.create_index(op.f('idx_connection_attempts_decision_created_at'), 'connection_attempts', ['decision', 'created_at'], unique=False)
    op.drop_index('idx_connection_attempts_action_created_at', table_name='connection_attempts')
    op.create_index(op.f('idx_connection_attempts_action_created_at'), 'connection_attempts', ['action', 'created_at'], unique=False)
    op.alter_column('chat_messages', 'agent_trace',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
